#!/bin/bash
git checkout gh-pages
git checkout master -- index.html
git checkout master -- demo.html
git checkout master -- doc-configuration.html
git checkout master -- doc-setup.html
git checkout master -- public
git checkout master -- src
git checkout master -- tests
git checkout master -- doc
git checkout master -- dist
git add .
git commit -a -m "merge from master"
git push origin gh-pages
git checkout master
