#!/bin/bash
git checkout gh-pages
git checkout master -- index.html
git checkout master -- demo-basic.html
git checkout master -- public
git checkout master -- src
git checkout master -- tests
git checkout master -- doc
git add .
git commit -a -m "merge from master"
git push origin gh-pages
git checkout master
